project_id = "imds-super-admin"

[functions.provisioning-worker]
verify_jwt = false

[functions.integration-webhook]
verify_jwt = false

[functions.integration-worker]
verify_jwt = false

[functions.api-gateway]
verify_jwt = false

[functions.checkmate-adapter]
verify_jwt = false
