import { AlertTriangle, CheckCircle2, ClipboardList, HeartPulse, LifeBuoy, Plus, RefreshCw, Rocket, Search, ShieldCheck, TicketCheck, UsersRound, X } from 'lucide-react';
import { type FormEvent, useMemo, useRef, useState } from 'react';
import { useAuth } from '../../core/auth';
import { useSupport } from './SupportContext';
import type { CreateTicketInput, SupportTicketPriority, SupportTicketStatus } from './supportRepository';

const priorityLabels:Record<SupportTicketPriority,string>={low:'Низкий',normal:'Обычный',high:'Высокий',urgent:'Срочный',critical:'Критический'};
const statusLabels:Record<SupportTicketStatus,string>={new:'Новый',open:'Открыт',in_progress:'В работе',waiting_customer:'Ждём клиента',waiting_internal:'Внутреннее ожидание',resolved:'Решён',closed:'Закрыт',cancelled:'Отменён'};
const emptyTicket:CreateTicketInput={organizationId:'',productId:null,type:'question',priority:'normal',channel:'portal',subject:'',description:'',requesterName:''};
function riskClass(value:string){return value==='healthy'?'ok':value==='attention'?'warn':value==='at_risk'||value==='critical'?'danger':'muted'}
function statusClass(value:string){return ['resolved','closed','completed'].includes(value)?'ok':['critical','urgent','blocked'].includes(value)?'danger':['waiting_customer','waiting_internal','attention'].includes(value)?'warn':'info'}
function formatDate(value:string|null){return value?new Intl.DateTimeFormat('ru-RU',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(value)):'—'}

export function SupportPage(){
 const {can,isDemo}=useAuth();
 const {tickets,customers,onboarding,organizations,products,loading,saving,error,refresh,createTicket,transition,createOnboarding,updateStep,refreshScores}=useSupport();
 const [tab,setTab]=useState<'tickets'|'customers'|'onboarding'>('tickets');const [query,setQuery]=useState('');const [ticketForm,setTicketForm]=useState(emptyTicket);const [validation,setValidation]=useState('');const [onboardingOrg,setOnboardingOrg]=useState('');const [goLive,setGoLive]=useState('');
 const ticketDialog=useRef<HTMLDialogElement|null>(null);const onboardingDialog=useRef<HTMLDialogElement|null>(null);const canManage=can('support.manage');
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return tickets.filter(t=>!q||[t.ticketNumber,t.organizationName,t.productName,t.subject].some(v=>v.toLowerCase().includes(q)))},[tickets,query]);
 const metrics={open:tickets.filter(t=>!['resolved','closed','cancelled'].includes(t.status)).length,breached:tickets.filter(t=>t.firstResponseBreached||t.resolutionBreached).length,atRisk:customers.filter(c=>['at_risk','critical'].includes(c.riskLevel)).length,onboarding:onboarding.filter(p=>p.progressPercent<100).length};
 const submitTicket=async(e:FormEvent)=>{e.preventDefault();if(!ticketForm.organizationId||ticketForm.subject.trim().length<3||ticketForm.description.trim().length<5){setValidation('Компания, тема и описание обязательны.');return}if(await createTicket({...ticketForm,subject:ticketForm.subject.trim(),description:ticketForm.description.trim()}))ticketDialog.current?.close()};
 const move=async(id:string,status:SupportTicketStatus)=>{const reason=window.prompt(`Причина перехода в статус «${statusLabels[status]}»:`);if(reason?.trim())await transition(id,status,reason.trim())};
 const submitOnboarding=async(e:FormEvent)=>{e.preventDefault();if(!onboardingOrg){setValidation('Выберите компанию.');return}if(await createOnboarding(onboardingOrg,goLive||null))onboardingDialog.current?.close()};
 return <>
  <div className="page-heading"><div><span className="eyebrow">Customer Success Control Plane</span><h1>Поддержка и успех клиента</h1><p>Онбординг, обращения, SLA, customer health и контроль следующих действий.</p></div><div className="heading-actions"><button className="secondary-button compact" onClick={()=>void refresh()} disabled={loading||saving}><RefreshCw className={loading?'spin':''} size={16}/> Обновить</button>{canManage&&<button className="primary-button" onClick={()=>{setTicketForm({...emptyTicket,organizationId:organizations[0]?.id||''});setValidation('');ticketDialog.current?.showModal()}}><Plus size={17}/> Новое обращение</button>}</div></div>
  {isDemo&&<div className="mode-banner"><ShieldCheck size={18}/><div><strong>Демо-режим Customer Success</strong><span>Данные сохраняются в браузере. Production-режим использует migration 0018 и защищённые RPC.</span></div></div>}
  {error&&<div className="error-banner"><AlertTriangle size={18}/><span>{error}</span></div>}
  <section className="metrics support-metrics"><article className="metric-card"><div className="metric-icon"><LifeBuoy size={21}/></div><div><span>Открытые обращения</span><strong>{metrics.open}</strong><small>в общей очереди</small></div></article><article className="metric-card"><div className="metric-icon"><AlertTriangle size={21}/></div><div><span>SLA breach</span><strong>{metrics.breached}</strong><small>требуют эскалации</small></div></article><article className="metric-card"><div className="metric-icon"><HeartPulse size={21}/></div><div><span>Клиенты в риске</span><strong>{metrics.atRisk}</strong><small>health ниже нормы</small></div></article><article className="metric-card"><div className="metric-icon"><Rocket size={21}/></div><div><span>Активный онбординг</span><strong>{metrics.onboarding}</strong><small>до go-live</small></div></article></section>
  <div className="tabs"><button className={tab==='tickets'?'active':''} onClick={()=>setTab('tickets')}><TicketCheck size={16}/> Обращения</button><button className={tab==='customers'?'active':''} onClick={()=>setTab('customers')}><UsersRound size={16}/> Customer Health</button><button className={tab==='onboarding'?'active':''} onClick={()=>setTab('onboarding')}><ClipboardList size={16}/> Онбординг</button></div>
  {tab==='tickets'&&<section className="panel"><div className="panel-header"><div><h2>Support Queue</h2><p>Единая очередь с приоритетами и SLA</p></div><div className="search support-search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Номер, компания, продукт..."/></div></div><div className="table-wrap"><table><thead><tr><th>Обращение</th><th>Компания</th><th>Приоритет</th><th>Статус</th><th>Исполнитель</th><th>SLA</th><th/></tr></thead><tbody>{filtered.map(t=><tr key={t.id}><td><strong>{t.ticketNumber}</strong><span>{t.subject}<br/><small>{t.productName}</small></span></td><td>{t.organizationName}</td><td><span className={`status ${statusClass(t.priority)}`}>{priorityLabels[t.priority]}</span></td><td><span className={`status ${statusClass(t.status)}`}>{statusLabels[t.status]}</span></td><td>{t.assignedTo}</td><td>{t.firstResponseBreached||t.resolutionBreached?<span className="status danger">Нарушен</span>:formatDate(t.resolutionDueAt)}</td><td>{canManage&&!['resolved','closed','cancelled'].includes(t.status)&&<div className="row-actions"><button className="row-button" onClick={()=>void move(t.id,'in_progress')} title="В работу"><RefreshCw size={15}/></button><button className="row-button" onClick={()=>void move(t.id,'resolved')} title="Решить"><CheckCircle2 size={15}/></button></div>}</td></tr>)}</tbody></table></div></section>}
  {tab==='customers'&&<section className="support-customer-grid">{customers.map(c=><article className="panel customer-health-card" key={c.organizationId}><div className="customer-health-head"><div><h3>{c.organizationName}</h3><span>{c.lifecycleStage} · {c.ownerName}</span></div><strong className={riskClass(c.riskLevel)}>{c.healthScore}</strong></div><div className="health"><div><span style={{width:`${c.healthScore}%`}}/></div><b>{c.healthScore}%</b></div><dl><div><dt>Risk</dt><dd><span className={`status ${riskClass(c.riskLevel)}`}>{c.riskLevel}</span></dd></div><div><dt>Онбординг</dt><dd>{c.onboardingScore}%</dd></div><div><dt>Последний контакт</dt><dd>{formatDate(c.lastContactAt)}</dd></div><div><dt>Следующий контакт</dt><dd>{formatDate(c.nextContactAt)}</dd></div></dl></article>)}</section>}
  {tab==='customers'&&canManage&&<div className="support-footer-action"><button className="secondary-button" onClick={()=>void refreshScores()} disabled={saving}><HeartPulse size={16}/> Пересчитать health score</button></div>}
  {tab==='onboarding'&&<><div className="support-toolbar">{canManage&&<button className="primary-button" onClick={()=>{setOnboardingOrg(organizations[0]?.id||'');setGoLive('');setValidation('');onboardingDialog.current?.showModal()}}><Plus size={16}/> Создать план</button>}</div><section className="support-onboarding-grid">{onboarding.map(plan=><article className="panel" key={plan.id}><div className="panel-header"><div><h2>{plan.organizationName}</h2><p>{plan.stage} · Go-live: {plan.targetGoLiveAt||'не задан'}</p></div><strong>{plan.progressPercent}%</strong></div><div className="health"><div><span style={{width:`${plan.progressPercent}%`}}/></div><b>{plan.progressPercent}%</b></div><div className="onboarding-steps">{plan.steps.sort((a,b)=>a.displayOrder-b.displayOrder).map(step=><div key={step.id}><span className={`step-dot ${step.status}`}/><div><strong>{step.title}</strong><small>{step.status}</small></div>{canManage&&!['completed','skipped'].includes(step.status)&&<button className="row-button" onClick={()=>void updateStep(step.id,'completed','Выполнено через Super Admin')}><CheckCircle2 size={15}/></button>}</div>)}</div></article>)}</section></>}
  <dialog ref={ticketDialog} className="modal"><form onSubmit={submitTicket}><div className="modal-header"><div><span className="eyebrow">Support Queue</span><h2>Новое обращение</h2></div><button type="button" className="icon-button" onClick={()=>ticketDialog.current?.close()}><X size={18}/></button></div><div className="form-grid"><label><span>Компания *</span><select value={ticketForm.organizationId} onChange={e=>setTicketForm({...ticketForm,organizationId:e.target.value})}>{organizations.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label><label><span>Продукт</span><select value={ticketForm.productId||''} onChange={e=>setTicketForm({...ticketForm,productId:e.target.value||null})}><option value="">Без продукта</option>{products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label><span>Тип</span><select value={ticketForm.type} onChange={e=>setTicketForm({...ticketForm,type:e.target.value})}><option value="incident">Инцидент</option><option value="problem">Проблема</option><option value="question">Вопрос</option><option value="request">Запрос</option><option value="onboarding">Онбординг</option><option value="billing">Биллинг</option><option value="integration">Интеграция</option></select></label><label><span>Приоритет</span><select value={ticketForm.priority} onChange={e=>setTicketForm({...ticketForm,priority:e.target.value as SupportTicketPriority})}>{Object.entries(priorityLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label className="span-2"><span>Тема *</span><input value={ticketForm.subject} onChange={e=>setTicketForm({...ticketForm,subject:e.target.value})}/></label><label className="span-2"><span>Описание *</span><textarea rows={5} value={ticketForm.description} onChange={e=>setTicketForm({...ticketForm,description:e.target.value})}/></label><label className="span-2"><span>Контакт клиента</span><input value={ticketForm.requesterName} onChange={e=>setTicketForm({...ticketForm,requesterName:e.target.value})}/></label></div>{validation&&<div className="form-message">{validation}</div>}<div className="modal-actions"><button type="button" className="secondary-button" onClick={()=>ticketDialog.current?.close()}>Отмена</button><button className="primary-button" disabled={saving}>Создать</button></div></form></dialog>
  <dialog ref={onboardingDialog} className="modal"><form onSubmit={submitOnboarding}><div className="modal-header"><div><span className="eyebrow">Customer Success</span><h2>Новый план онбординга</h2></div><button type="button" className="icon-button" onClick={()=>onboardingDialog.current?.close()}><X size={18}/></button></div><div className="form-grid"><label className="span-2"><span>Компания *</span><select value={onboardingOrg} onChange={e=>setOnboardingOrg(e.target.value)}>{organizations.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label><label className="span-2"><span>Плановый go-live</span><input type="date" value={goLive} onChange={e=>setGoLive(e.target.value)}/></label></div>{validation&&<div className="form-message">{validation}</div>}<div className="modal-actions"><button type="button" className="secondary-button" onClick={()=>onboardingDialog.current?.close()}>Отмена</button><button className="primary-button" disabled={saving}>Создать план</button></div></form></dialog>
 </>
}
