import { platformModules, type PlatformModuleDefinition } from './moduleRuntimeRepository';

const releasedAt = '2026-08-02T15:00:00.000Z';

const crmModules: PlatformModuleDefinition[] = [
  {
    id: 'module-crm-contacts',
    code: 'crm.contacts',
    name: 'Контакты и компании',
    description: 'Единая база клиентов, компаний, реквизитов, тегов и истории взаимодействий.',
    category: 'CRM',
    ownerProductCode: 'imds-crm',
    ownerProductName: 'IMDS CRM',
    compatibleHostProducts: [
      { code: 'imds-marketing', name: 'IMDS Marketing' },
      { code: 'imds-mis', name: 'IMDS MIS' },
    ],
    defaultRoute: '/crm/contacts',
    placement: 'sidebar.crm',
    permissions: ['crm.contacts.read', 'crm.contacts.create', 'crm.contacts.update', 'crm.companies.read'],
    versions: [{ id: 'crm-contacts-1-0-0', version: '1.0.0', channel: 'stable', status: 'published', releasedAt }],
    price: { code: 'crm-contacts-monthly-kzt', monthlyAmountMinor: 1_500_000, currency: 'KZT' },
    limits: { contacts: 10000, companies: 2000, customFields: 50 },
    provisioningPlan: ['validate_entitlement', 'ensure_contact_workspace', 'ensure_default_fields', 'health_check'],
  },
  {
    id: 'module-crm-deals',
    code: 'crm.deals',
    name: 'Сделки',
    description: 'Карточки сделок, суммы, ответственные, источники, товары и история изменений.',
    category: 'CRM',
    ownerProductCode: 'imds-crm',
    ownerProductName: 'IMDS CRM',
    compatibleHostProducts: [
      { code: 'imds-marketing', name: 'IMDS Marketing' },
      { code: 'imds-finance', name: 'IMDS Finance' },
    ],
    defaultRoute: '/crm/deals',
    placement: 'sidebar.crm',
    permissions: ['crm.deals.read', 'crm.deals.create', 'crm.deals.update', 'crm.deals.delete'],
    versions: [{ id: 'crm-deals-1-0-0', version: '1.0.0', channel: 'stable', status: 'published', releasedAt }],
    price: { code: 'crm-deals-monthly-kzt', monthlyAmountMinor: 2_000_000, currency: 'KZT' },
    limits: { dealsPerMonth: 5000, productsPerDeal: 100, customFields: 80 },
    provisioningPlan: ['validate_entitlement', 'ensure_deal_schema', 'ensure_default_sources', 'health_check'],
  },
  {
    id: 'module-crm-pipelines',
    code: 'crm.pipelines',
    name: 'Воронки продаж',
    description: 'Несколько воронок, этапы, правила переходов, причины отказа и SLA по стадиям.',
    category: 'CRM',
    ownerProductCode: 'imds-crm',
    ownerProductName: 'IMDS CRM',
    compatibleHostProducts: [{ code: 'imds-marketing', name: 'IMDS Marketing' }],
    defaultRoute: '/crm/pipelines',
    placement: 'sidebar.crm',
    permissions: ['crm.pipelines.read', 'crm.pipelines.create', 'crm.pipelines.update', 'crm.stages.manage'],
    versions: [{ id: 'crm-pipelines-1-0-0', version: '1.0.0', channel: 'stable', status: 'published', releasedAt }],
    price: { code: 'crm-pipelines-monthly-kzt', monthlyAmountMinor: 1_800_000, currency: 'KZT' },
    limits: { pipelines: 10, stagesPerPipeline: 30, transitionRules: 100 },
    provisioningPlan: ['validate_entitlement', 'ensure_main_pipeline', 'ensure_default_stages', 'health_check'],
  },
  {
    id: 'module-crm-tasks',
    code: 'crm.tasks',
    name: 'Задачи и активности',
    description: 'Звонки, встречи, напоминания, чек-листы, просрочки и контроль выполнения.',
    category: 'Productivity',
    ownerProductCode: 'imds-crm',
    ownerProductName: 'IMDS CRM',
    compatibleHostProducts: [
      { code: 'imds-marketing', name: 'IMDS Marketing' },
      { code: 'imds-mis', name: 'IMDS MIS' },
    ],
    defaultRoute: '/crm/tasks',
    placement: 'sidebar.tasks',
    permissions: ['crm.tasks.read', 'crm.tasks.create', 'crm.tasks.update', 'crm.tasks.assign'],
    versions: [{ id: 'crm-tasks-1-0-0', version: '1.0.0', channel: 'stable', status: 'published', releasedAt }],
    price: { code: 'crm-tasks-monthly-kzt', monthlyAmountMinor: 1_200_000, currency: 'KZT' },
    limits: { activeTasks: 10000, checklistsPerTask: 20, remindersPerTask: 10 },
    provisioningPlan: ['validate_entitlement', 'ensure_task_workspace', 'ensure_notification_rules', 'health_check'],
  },
  {
    id: 'module-crm-chats',
    code: 'crm.chats',
    name: 'Омниканальные чаты',
    description: 'Общая лента WhatsApp, Instagram, Telegram и веб-чатов с привязкой к клиенту и сделке.',
    category: 'Communications',
    ownerProductCode: 'imds-crm',
    ownerProductName: 'IMDS CRM',
    compatibleHostProducts: [{ code: 'imds-marketing', name: 'IMDS Marketing' }],
    defaultRoute: '/crm/chats',
    placement: 'sidebar.communications',
    permissions: ['crm.chats.read', 'crm.messages.send', 'crm.conversations.assign', 'crm.templates.use'],
    versions: [{ id: 'crm-chats-0-9-0', version: '0.9.0', channel: 'beta', status: 'published', releasedAt }],
    price: { code: 'crm-chats-monthly-kzt', monthlyAmountMinor: 3_500_000, currency: 'KZT' },
    limits: { channels: 10, operators: 30, messagesPerMonth: 50000 },
    provisioningPlan: ['validate_entitlement', 'ensure_inbox', 'ensure_channel_registry', 'ensure_realtime_topics', 'health_check'],
  },
  {
    id: 'module-crm-analytics',
    code: 'crm.analytics',
    name: 'CRM Аналитика',
    description: 'Конверсия, скорость прохождения этапов, продажи, менеджеры, источники и прогноз выручки.',
    category: 'Analytics',
    ownerProductCode: 'imds-crm',
    ownerProductName: 'IMDS CRM',
    compatibleHostProducts: [
      { code: 'imds-marketing', name: 'IMDS Marketing' },
      { code: 'imds-dashboard', name: 'IMDS Dashboard' },
    ],
    defaultRoute: '/crm/analytics',
    placement: 'sidebar.analytics',
    permissions: ['crm.analytics.read', 'crm.analytics.export', 'crm.forecast.read'],
    versions: [{ id: 'crm-analytics-1-0-0', version: '1.0.0', channel: 'stable', status: 'published', releasedAt }],
    price: { code: 'crm-analytics-monthly-kzt', monthlyAmountMinor: 2_800_000, currency: 'KZT' },
    limits: { dashboards: 20, exportsPerMonth: 100, dataRetentionDays: 730 },
    provisioningPlan: ['validate_entitlement', 'ensure_analytics_views', 'ensure_rollups', 'health_check'],
  },
];

for (const module of crmModules) {
  if (!platformModules.some((existing) => existing.code === module.code)) platformModules.push(module);
}
