-- IMDS Customer Success and Support Center.
-- Staff writes are exposed only through guarded RPC functions.

create type public.support_ticket_priority as enum ('low', 'normal', 'high', 'urgent');
create type public.support_ticket_status as enum ('new', 'open', 'pending_customer', 'pending_internal', 'resolved', 'closed');
create type public.support_ticket_channel as enum ('portal', 'email', 'whatsapp', 'phone', 'internal');
create type public.support_author_type as enum ('customer', 'staff', 'system');

create table public.support_tickets (
  id uuid primary key default gen_random_uuid(),
  ticket_number bigint generated by default as identity unique,
  organization_id uuid not null references public.organizations(id) on delete restrict,
  product_id uuid references public.products(id) on delete set null,
  subject text not null,
  description text,
  category text not null default 'Другое',
  priority public.support_ticket_priority not null default 'normal',
  status public.support_ticket_status not null default 'new',
  channel public.support_ticket_channel not null default 'portal',
  requester_name text,
  requester_email text,
  assignee_id uuid references public.platform_users(id) on delete set null,
  first_response_due_at timestamptz,
  resolution_due_at timestamptz,
  first_responded_at timestamptz,
  resolved_at timestamptz,
  last_message_at timestamptz not null default now(),
  created_by uuid references public.platform_users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (char_length(btrim(subject)) between 3 and 240),
  check (requester_email is null or requester_email = '' or requester_email ~* '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$'),
  check (resolved_at is null or resolved_at >= created_at),
  check (first_responded_at is null or first_responded_at >= created_at)
);

create table public.support_messages (
  id uuid primary key default gen_random_uuid(),
  ticket_id uuid not null references public.support_tickets(id) on delete cascade,
  author_id uuid references public.platform_users(id) on delete set null,
  author_name text,
  author_type public.support_author_type not null,
  body text not null,
  is_internal boolean not null default false,
  created_at timestamptz not null default now(),
  check (char_length(btrim(body)) between 1 and 20000),
  check (not is_internal or author_type <> 'customer')
);

create table public.support_events (
  id uuid primary key default gen_random_uuid(),
  ticket_id uuid not null references public.support_tickets(id) on delete cascade,
  event_type text not null,
  actor_id uuid references public.platform_users(id) on delete set null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  check (event_type ~ '^[a-z0-9]+([._-][a-z0-9]+)*$')
);

create index support_tickets_queue_idx on public.support_tickets(status, priority, last_message_at desc);
create index support_tickets_organization_idx on public.support_tickets(organization_id, created_at desc);
create index support_tickets_assignee_idx on public.support_tickets(assignee_id, status) where status not in ('resolved', 'closed');
create index support_tickets_sla_idx on public.support_tickets(first_response_due_at, resolution_due_at) where status not in ('resolved', 'closed');
create index support_messages_ticket_idx on public.support_messages(ticket_id, created_at);
create index support_events_ticket_idx on public.support_events(ticket_id, created_at desc);

create trigger support_tickets_set_updated_at
before update on public.support_tickets
for each row execute function public.set_updated_at();

create or replace function public.prevent_support_event_mutation()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  raise exception 'Support events are append-only';
end;
$$;

create trigger support_events_immutable
before update or delete on public.support_events
for each row execute function public.prevent_support_event_mutation();

create or replace function public.can_manage_support()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.has_global_role(array[
    'platform_owner'::public.global_role,
    'super_admin'::public.global_role,
    'support_admin'::public.global_role,
    'technical_admin'::public.global_role,
    'sales_manager'::public.global_role
  ]);
$$;

revoke all on function public.can_manage_support() from public;
grant execute on function public.can_manage_support() to authenticated;

create or replace function public.support_sla_deadlines(
  priority_value public.support_ticket_priority,
  created_at_value timestamptz default now()
)
returns table (first_response_due_at timestamptz, resolution_due_at timestamptz)
language sql
immutable
set search_path = public
as $$
  select
    created_at_value + case priority_value
      when 'urgent' then interval '15 minutes'
      when 'high' then interval '1 hour'
      when 'normal' then interval '4 hours'
      else interval '8 hours'
    end,
    created_at_value + case priority_value
      when 'urgent' then interval '4 hours'
      when 'high' then interval '8 hours'
      when 'normal' then interval '24 hours'
      else interval '48 hours'
    end;
$$;

create or replace function public.create_support_ticket(
  organization_id_value uuid,
  product_id_value uuid,
  subject_value text,
  description_value text,
  category_value text,
  priority_value public.support_ticket_priority,
  channel_value public.support_ticket_channel,
  requester_name_value text,
  requester_email_value text
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  ticket_id_value uuid;
  created_at_value timestamptz := now();
  response_due timestamptz;
  resolution_due timestamptz;
begin
  if not public.can_manage_support() then raise exception 'Insufficient permission to create support tickets'; end if;
  if not exists (select 1 from public.organizations where id = organization_id_value and archived_at is null) then raise exception 'Organization is unavailable'; end if;
  if product_id_value is not null and not exists (select 1 from public.products where id = product_id_value and archived_at is null) then raise exception 'Product is unavailable'; end if;
  if char_length(btrim(subject_value)) < 3 then raise exception 'Ticket subject is required'; end if;
  if char_length(btrim(description_value)) < 3 then raise exception 'Ticket description is required'; end if;

  select first_response_due_at, resolution_due_at into response_due, resolution_due
  from public.support_sla_deadlines(priority_value, created_at_value);

  insert into public.support_tickets (
    organization_id, product_id, subject, description, category, priority, status, channel,
    requester_name, requester_email, first_response_due_at, resolution_due_at, created_by, created_at, updated_at
  ) values (
    organization_id_value, product_id_value, btrim(subject_value), btrim(description_value), coalesce(nullif(btrim(category_value), ''), 'Другое'),
    priority_value, 'new', channel_value, nullif(btrim(requester_name_value), ''), nullif(lower(btrim(requester_email_value)), ''),
    response_due, resolution_due, auth.uid(), created_at_value, created_at_value
  ) returning id into ticket_id_value;

  insert into public.support_messages (ticket_id, author_name, author_type, body, is_internal, created_at)
  values (ticket_id_value, coalesce(nullif(btrim(requester_name_value), ''), 'Клиент'), 'customer', btrim(description_value), false, created_at_value);

  insert into public.support_events (ticket_id, event_type, actor_id, payload)
  values (ticket_id_value, 'ticket.created', auth.uid(), jsonb_build_object('priority', priority_value, 'channel', channel_value));

  return ticket_id_value;
end;
$$;

revoke all on function public.create_support_ticket(uuid, uuid, text, text, text, public.support_ticket_priority, public.support_ticket_channel, text, text) from public;
grant execute on function public.create_support_ticket(uuid, uuid, text, text, text, public.support_ticket_priority, public.support_ticket_channel, text, text) to authenticated;

create or replace function public.add_support_message(
  ticket_id_value uuid,
  body_value text,
  is_internal_value boolean default false
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  message_id_value uuid;
  staff_name text;
  current_status public.support_ticket_status;
begin
  if not public.can_manage_support() then raise exception 'Insufficient permission to reply to support tickets'; end if;
  if char_length(btrim(body_value)) < 1 then raise exception 'Message body is required'; end if;

  select status into current_status from public.support_tickets where id = ticket_id_value for update;
  if not found then raise exception 'Support ticket not found'; end if;
  if current_status = 'closed' then raise exception 'Closed support ticket cannot receive messages'; end if;

  select coalesce(nullif(full_name, ''), email, 'Support') into staff_name from public.platform_users where id = auth.uid();

  insert into public.support_messages (ticket_id, author_id, author_name, author_type, body, is_internal)
  values (ticket_id_value, auth.uid(), coalesce(staff_name, 'Support'), 'staff', btrim(body_value), is_internal_value)
  returning id into message_id_value;

  update public.support_tickets
  set first_responded_at = coalesce(first_responded_at, case when not is_internal_value then now() else null end),
      status = case when status = 'new' and not is_internal_value then 'open' else status end,
      last_message_at = now()
  where id = ticket_id_value;

  insert into public.support_events (ticket_id, event_type, actor_id, payload)
  values (ticket_id_value, case when is_internal_value then 'message.internal_added' else 'message.staff_added' end, auth.uid(), jsonb_build_object('messageId', message_id_value));

  return message_id_value;
end;
$$;

revoke all on function public.add_support_message(uuid, text, boolean) from public;
grant execute on function public.add_support_message(uuid, text, boolean) to authenticated;

create or replace function public.update_support_ticket(
  ticket_id_value uuid,
  status_value public.support_ticket_status,
  priority_value public.support_ticket_priority,
  assignee_id_value uuid
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  before_record jsonb;
  response_due timestamptz;
  resolution_due timestamptz;
begin
  if not public.can_manage_support() then raise exception 'Insufficient permission to update support tickets'; end if;
  if assignee_id_value is not null and not exists (select 1 from public.platform_users where id = assignee_id_value and is_active) then raise exception 'Assignee is unavailable'; end if;

  select to_jsonb(ticket) into before_record from public.support_tickets ticket where id = ticket_id_value for update;
  if before_record is null then raise exception 'Support ticket not found'; end if;

  if priority_value::text <> before_record->>'priority' then
    select first_response_due_at, resolution_due_at into response_due, resolution_due
    from public.support_sla_deadlines(priority_value, (before_record->>'created_at')::timestamptz);
  end if;

  update public.support_tickets
  set status = status_value,
      priority = priority_value,
      assignee_id = assignee_id_value,
      first_response_due_at = coalesce(response_due, first_response_due_at),
      resolution_due_at = coalesce(resolution_due, resolution_due_at),
      resolved_at = case when status_value in ('resolved', 'closed') then coalesce(resolved_at, now()) else null end
  where id = ticket_id_value;

  insert into public.support_events (ticket_id, event_type, actor_id, payload)
  values (ticket_id_value, 'ticket.updated', auth.uid(), jsonb_build_object(
    'before', before_record,
    'status', status_value,
    'priority', priority_value,
    'assigneeId', assignee_id_value
  ));
end;
$$;

revoke all on function public.update_support_ticket(uuid, public.support_ticket_status, public.support_ticket_priority, uuid) from public;
grant execute on function public.update_support_ticket(uuid, public.support_ticket_status, public.support_ticket_priority, uuid) to authenticated;

create view public.support_ticket_overview
with (security_invoker = true)
as
select
  ticket.id,
  ticket.ticket_number,
  ticket.organization_id,
  organization.name as organization_name,
  ticket.product_id,
  product.name as product_name,
  ticket.subject,
  ticket.description,
  ticket.category,
  ticket.priority,
  ticket.status,
  ticket.channel,
  ticket.requester_name,
  ticket.requester_email,
  ticket.assignee_id,
  coalesce(nullif(assignee.full_name, ''), assignee.email) as assignee_name,
  ticket.first_response_due_at,
  ticket.resolution_due_at,
  ticket.first_responded_at,
  ticket.resolved_at,
  ticket.last_message_at,
  ticket.created_at,
  ticket.updated_at
from public.support_tickets ticket
join public.organizations organization on organization.id = ticket.organization_id
left join public.products product on product.id = ticket.product_id
left join public.platform_users assignee on assignee.id = ticket.assignee_id;

alter table public.support_tickets enable row level security;
alter table public.support_messages enable row level security;
alter table public.support_events enable row level security;

create policy support_tickets_staff_select on public.support_tickets for select to authenticated using (public.is_platform_staff());
create policy support_messages_staff_select on public.support_messages for select to authenticated using (public.is_platform_staff());
create policy support_events_staff_select on public.support_events for select to authenticated using (public.is_platform_staff());

revoke insert, update, delete on public.support_tickets from authenticated;
revoke insert, update, delete on public.support_messages from authenticated;
revoke insert, update, delete on public.support_events from authenticated;

grant select on public.support_tickets to authenticated;
grant select on public.support_messages to authenticated;
grant select on public.support_events to authenticated;
grant select on public.support_ticket_overview to authenticated;

grant all on public.support_tickets to service_role;
grant all on public.support_messages to service_role;
grant all on public.support_events to service_role;
grant select on public.support_ticket_overview to service_role;

comment on table public.support_tickets is 'Platform support tickets with organization, product, ownership and SLA deadlines.';
comment on table public.support_messages is 'Customer-visible replies and internal support notes.';
comment on table public.support_events is 'Append-only ticket lifecycle and audit stream.';
