import { AlertTriangle, BadgeDollarSign, Banknote, CheckCircle2, CircleDollarSign, Clock3, FileText, Plus, RefreshCw, RotateCcw, WalletCards } from 'lucide-react';
import { type FormEvent, useMemo, useRef, useState } from 'react';
import { useAuth } from '../../core/auth';
import { useBillingOperations } from './BillingOperationsContext';
import type { InvoiceStatus, PaymentMethod, RefundStatus } from './billingOperationsRepository';

const invoiceLabels: Record<InvoiceStatus, string> = {
  draft: 'Черновик', issued: 'Выставлен', partially_paid: 'Частично оплачен', paid: 'Оплачен', overdue: 'Просрочен', void: 'Аннулирован', written_off: 'Списан',
};
const refundLabels: Record<RefundStatus, string> = {
  requested: 'Запрошен', pending_approval: 'На согласовании', approved: 'Одобрен', processing: 'Обрабатывается', succeeded: 'Выполнен', failed: 'Ошибка', rejected: 'Отклонён', cancelled: 'Отменён',
};

function money(value: number, currency = 'KZT') {
  return new Intl.NumberFormat('ru-RU', { style: 'currency', currency, maximumFractionDigits: 0 }).format(value);
}
function date(value: string | null) {
  return value ? new Intl.DateTimeFormat('ru-RU', { day: '2-digit', month: 'short', year: 'numeric' }).format(new Date(value)) : '—';
}
function badge(status: string) {
  if (['paid', 'succeeded', 'resolved'].includes(status)) return 'ok';
  if (['overdue', 'failed', 'rejected'].includes(status)) return 'danger';
  if (['partially_paid', 'pending_approval', 'processing', 'open', 'promised'].includes(status)) return 'warn';
  return 'muted';
}

export function BillingOperationsPage() {
  const { can, isDemo } = useAuth();
  const data = useBillingOperations();
  const canManage = can('billing.operations.manage');
  const [tab, setTab] = useState<'invoices' | 'payments' | 'refunds' | 'dunning'>('invoices');
  const [query, setQuery] = useState('');
  const [selectedInvoiceId, setSelectedInvoiceId] = useState<string | null>(null);
  const invoiceDialog = useRef<HTMLDialogElement | null>(null);
  const lineDialog = useRef<HTMLDialogElement | null>(null);
  const paymentDialog = useRef<HTMLDialogElement | null>(null);
  const allocationDialog = useRef<HTMLDialogElement | null>(null);
  const refundDialog = useRef<HTMLDialogElement | null>(null);
  const [validation, setValidation] = useState('');
  const today = new Date().toISOString().slice(0, 10);
  const nextMonth = new Date(Date.now() + 30 * 86400000).toISOString().slice(0, 10);
  const [invoiceForm, setInvoiceForm] = useState({ organizationId: '', subscriptionId: '', currency: 'KZT', periodStart: today, periodEnd: nextMonth, dueAt: today, notes: '' });
  const [lineForm, setLineForm] = useState({ lineType: 'subscription', description: '', quantity: 1, unitPrice: 0, discountAmount: 0, taxRate: 0 });
  const [paymentForm, setPaymentForm] = useState({ organizationId: '', amount: 0, currency: 'KZT', method: 'bank_transfer' as PaymentMethod, receivedAt: today, externalReference: '', payerName: '' });
  const [allocationForm, setAllocationForm] = useState({ paymentId: '', invoiceId: '', amount: 0 });
  const [refundForm, setRefundForm] = useState({ paymentId: '', amount: 0, reason: '' });

  const metrics = useMemo(() => ({
    receivables: data.invoices.reduce((sum, item) => sum + item.outstandingTotal, 0),
    overdue: data.invoices.filter((item) => item.status === 'overdue').reduce((sum, item) => sum + item.outstandingTotal, 0),
    received: data.payments.filter((item) => ['succeeded', 'partially_refunded', 'refunded'].includes(item.status)).reduce((sum, item) => sum + item.amount, 0),
    pendingRefunds: data.refunds.filter((item) => !['succeeded', 'rejected', 'cancelled'].includes(item.status)).reduce((sum, item) => sum + item.amount, 0),
  }), [data.invoices, data.payments, data.refunds]);

  const normalized = query.trim().toLowerCase();
  const invoices = data.invoices.filter((item) => !normalized || [item.organizationName, item.invoiceNumber, item.status].some((value) => value.toLowerCase().includes(normalized)));
  const payments = data.payments.filter((item) => !normalized || [item.organizationName, item.paymentNumber, item.externalReference].some((value) => value.toLowerCase().includes(normalized)));
  const refunds = data.refunds.filter((item) => !normalized || [item.organizationName, item.refundNumber, item.reason].some((value) => value.toLowerCase().includes(normalized)));
  const selectedInvoice = selectedInvoiceId ? data.invoices.find((item) => item.id === selectedInvoiceId) : null;

  const openInvoice = () => {
    const organization = data.organizations[0];
    const subscription = data.subscriptions.find((item) => item.organizationId === organization?.id);
    setInvoiceForm({ organizationId: organization?.id ?? '', subscriptionId: subscription?.id ?? '', currency: subscription?.currency ?? 'KZT', periodStart: today, periodEnd: nextMonth, dueAt: today, notes: '' });
    setValidation(''); invoiceDialog.current?.showModal();
  };
  const submitInvoice = async (event: FormEvent) => {
    event.preventDefault();
    if (!invoiceForm.organizationId || !invoiceForm.periodStart || !invoiceForm.periodEnd || !invoiceForm.dueAt) return setValidation('Заполните компанию, период и срок оплаты.');
    if (new Date(invoiceForm.periodEnd) <= new Date(invoiceForm.periodStart)) return setValidation('Конец периода должен быть позже начала.');
    if (await data.createInvoice({ ...invoiceForm, subscriptionId: invoiceForm.subscriptionId || null })) invoiceDialog.current?.close();
  };
  const openLine = (invoiceId: string) => { setSelectedInvoiceId(invoiceId); setLineForm({ lineType: 'subscription', description: '', quantity: 1, unitPrice: 0, discountAmount: 0, taxRate: 0 }); setValidation(''); lineDialog.current?.showModal(); };
  const submitLine = async (event: FormEvent) => {
    event.preventDefault();
    if (!selectedInvoiceId || lineForm.description.trim().length < 3 || lineForm.quantity <= 0 || lineForm.unitPrice < 0) return setValidation('Проверьте описание, количество и цену.');
    if (await data.addInvoiceLine({ invoiceId: selectedInvoiceId, ...lineForm, description: lineForm.description.trim() })) lineDialog.current?.close();
  };
  const openPayment = () => { const organization = data.organizations[0]; setPaymentForm({ organizationId: organization?.id ?? '', amount: 0, currency: 'KZT', method: 'bank_transfer', receivedAt: today, externalReference: '', payerName: '' }); setValidation(''); paymentDialog.current?.showModal(); };
  const submitPayment = async (event: FormEvent) => { event.preventDefault(); if (!paymentForm.organizationId || paymentForm.amount <= 0) return setValidation('Выберите компанию и укажите положительную сумму.'); if (await data.recordPayment(paymentForm)) paymentDialog.current?.close(); };
  const openAllocation = (paymentId: string) => { const payment = data.payments.find((item) => item.id === paymentId); const invoice = data.invoices.find((item) => item.organizationId === payment?.organizationId && item.outstandingTotal > 0 && !['draft', 'void', 'written_off'].includes(item.status)); setAllocationForm({ paymentId, invoiceId: invoice?.id ?? '', amount: Math.min((payment?.amount ?? 0) - (payment?.allocatedAmount ?? 0), invoice?.outstandingTotal ?? 0) }); setValidation(''); allocationDialog.current?.showModal(); };
  const submitAllocation = async (event: FormEvent) => { event.preventDefault(); if (!allocationForm.invoiceId || allocationForm.amount <= 0) return setValidation('Выберите счёт и сумму распределения.'); if (await data.allocatePayment(allocationForm.paymentId, allocationForm.invoiceId, allocationForm.amount)) allocationDialog.current?.close(); };
  const openRefund = (paymentId: string) => { const payment = data.payments.find((item) => item.id === paymentId); setRefundForm({ paymentId, amount: Math.max((payment?.amount ?? 0) - (payment?.refundedAmount ?? 0), 0), reason: '' }); setValidation(''); refundDialog.current?.showModal(); };
  const submitRefund = async (event: FormEvent) => { event.preventDefault(); if (refundForm.amount <= 0 || refundForm.reason.trim().length < 10) return setValidation('Укажите сумму и подробную причину минимум из 10 символов.'); if (await data.requestRefund(refundForm.paymentId, refundForm.amount, refundForm.reason.trim())) refundDialog.current?.close(); };

  return <>
    <div className="page-heading"><div><span className="eyebrow">Commercial Control Plane</span><h1>Billing Operations</h1><p>Счета, поступления, распределение оплат, задолженность, возвраты и взыскание.</p></div><div className="heading-actions"><button className="secondary-button compact" onClick={() => void data.refresh()} disabled={data.loading || data.saving}><RefreshCw className={data.loading ? 'spin' : ''} size={16}/> Обновить</button>{canManage && <button className="primary-button" onClick={tab === 'payments' ? openPayment : openInvoice}><Plus size={17}/> {tab === 'payments' ? 'Записать платёж' : 'Новый счёт'}</button>}</div></div>
    {isDemo && <div className="mode-banner"><BadgeDollarSign size={18}/><div><strong>Демо-режим Billing Operations</strong><span>Операции сохраняются в браузере. В production все изменения выполняются через защищённые RPC.</span></div></div>}
    {data.error && <div className="error-banner"><AlertTriangle size={18}/><span>{data.error}</span></div>}
    <section className="metrics billing-operations-metrics"><article className="metric-card"><div className="metric-icon"><FileText size={21}/></div><div><span>Дебиторская задолженность</span><strong>{money(metrics.receivables)}</strong><small>{data.invoices.filter((item) => item.outstandingTotal > 0).length} открытых счетов</small></div></article><article className="metric-card"><div className="metric-icon"><Clock3 size={21}/></div><div><span>Просрочено</span><strong>{money(metrics.overdue)}</strong><small>{data.invoices.filter((item) => item.status === 'overdue').length} счетов</small></div></article><article className="metric-card"><div className="metric-icon"><Banknote size={21}/></div><div><span>Поступления</span><strong>{money(metrics.received)}</strong><small>{data.payments.length} платежей</small></div></article><article className="metric-card"><div className="metric-icon"><RotateCcw size={21}/></div><div><span>Возвраты в работе</span><strong>{money(metrics.pendingRefunds)}</strong><small>{data.refunds.filter((item) => item.status !== 'succeeded').length} операций</small></div></article></section>
    <div className="segmented-tabs"><button className={tab === 'invoices' ? 'active' : ''} onClick={() => setTab('invoices')}>Счета</button><button className={tab === 'payments' ? 'active' : ''} onClick={() => setTab('payments')}>Платежи</button><button className={tab === 'refunds' ? 'active' : ''} onClick={() => setTab('refunds')}>Возвраты</button><button className={tab === 'dunning' ? 'active' : ''} onClick={() => setTab('dunning')}>Взыскание</button></div>
    <div className="billing-toolbar"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Компания, номер документа, статус..."/></div>
    {tab === 'invoices' && <div className="panel"><div className="table-wrap"><table><thead><tr><th>Счёт</th><th>Компания</th><th>Статус</th><th>Сумма</th><th>Оплачено</th><th>Остаток</th><th>Срок</th><th/></tr></thead><tbody>{invoices.map((invoice) => <tr key={invoice.id}><td><strong>{invoice.invoiceNumber}</strong><span>{invoice.lines.length} позиций</span></td><td>{invoice.organizationName}</td><td><span className={`status ${badge(invoice.status)}`}>{invoiceLabels[invoice.status]}</span></td><td>{money(invoice.total, invoice.currency)}</td><td>{money(invoice.paidTotal, invoice.currency)}</td><td><strong>{money(invoice.outstandingTotal, invoice.currency)}</strong></td><td>{date(invoice.dueAt)}</td><td><div className="row-actions">{canManage && invoice.status === 'draft' && <><button className="secondary-button compact" onClick={() => openLine(invoice.id)}>Позиция</button><button className="primary-button compact" onClick={() => void data.issueInvoice(invoice.id)}>Выставить</button></>}</div></td></tr>)}</tbody></table></div></div>}
    {tab === 'payments' && <div className="panel"><div className="table-wrap"><table><thead><tr><th>Платёж</th><th>Компания</th><th>Метод</th><th>Сумма</th><th>Распределено</th><th>Возвращено</th><th>Дата</th><th/></tr></thead><tbody>{payments.map((payment) => <tr key={payment.id}><td><strong>{payment.paymentNumber}</strong><span>{payment.externalReference || 'без внешней ссылки'}</span></td><td>{payment.organizationName}</td><td>{payment.method}</td><td>{money(payment.amount, payment.currency)}</td><td>{money(payment.allocatedAmount, payment.currency)}</td><td>{money(payment.refundedAmount, payment.currency)}</td><td>{date(payment.receivedAt)}</td><td><div className="row-actions">{canManage && payment.allocatedAmount < payment.amount - payment.refundedAmount && <button className="secondary-button compact" onClick={() => openAllocation(payment.id)}>Распределить</button>}{canManage && payment.refundedAmount < payment.amount && <button className="danger-button compact" onClick={() => openRefund(payment.id)}>Возврат</button>}</div></td></tr>)}</tbody></table></div></div>}
    {tab === 'refunds' && <div className="panel"><div className="table-wrap"><table><thead><tr><th>Возврат</th><th>Компания</th><th>Статус</th><th>Сумма</th><th>Причина</th><th>Согласование</th><th/></tr></thead><tbody>{refunds.map((refund) => <tr key={refund.id}><td><strong>{refund.refundNumber}</strong><span>{date(refund.createdAt)}</span></td><td>{refund.organizationName}</td><td><span className={`status ${badge(refund.status)}`}>{refundLabels[refund.status]}</span></td><td>{money(refund.amount)}</td><td>{refund.reason}</td><td>{refund.approvalRequestId ? 'Требуется' : 'Не требуется'}</td><td>{canManage && refund.status === 'approved' && <button className="primary-button compact" onClick={() => { const reference = window.prompt('Внешний номер возврата:') ?? ''; if (reference.trim()) void data.completeRefund(refund.id, reference.trim()); }}><CheckCircle2 size={15}/> Завершить</button>}</td></tr>)}</tbody></table></div></div>}
    {tab === 'dunning' && <div className="dunning-grid">{data.dunningCases.map((item) => <article className="panel dunning-card" key={item.id}><div className="panel-header"><div><h2>{item.organizationName}</h2><p>{item.invoiceNumber}</p></div><span className={`status ${badge(item.status)}`}>Этап {item.stage}</span></div><p>{item.notes || 'Комментарий не указан.'}</p><dl><div><dt>Следующее действие</dt><dd>{date(item.nextActionAt)}</dd></div><div><dt>Обещанный платёж</dt><dd>{date(item.promisedPaymentAt)}</dd></div></dl></article>)}</div>}

    <dialog ref={invoiceDialog} className="modal"><form onSubmit={submitInvoice}><div className="modal-header"><div><span className="eyebrow">Invoice</span><h2>Новый счёт</h2></div><button type="button" className="icon-button" onClick={() => invoiceDialog.current?.close()}>×</button></div><div className="form-grid"><label><span>Компания</span><select value={invoiceForm.organizationId} onChange={(e) => { const orgId = e.target.value; const sub = data.subscriptions.find((item) => item.organizationId === orgId); setInvoiceForm({ ...invoiceForm, organizationId: orgId, subscriptionId: sub?.id ?? '', currency: sub?.currency ?? 'KZT' }); }}>{data.organizations.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label><span>Подписка</span><select value={invoiceForm.subscriptionId} onChange={(e) => setInvoiceForm({ ...invoiceForm, subscriptionId: e.target.value })}><option value="">Без подписки</option>{data.subscriptions.filter((item) => item.organizationId === invoiceForm.organizationId).map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select></label><label><span>Начало периода</span><input type="date" value={invoiceForm.periodStart} onChange={(e) => setInvoiceForm({ ...invoiceForm, periodStart: e.target.value })}/></label><label><span>Конец периода</span><input type="date" value={invoiceForm.periodEnd} onChange={(e) => setInvoiceForm({ ...invoiceForm, periodEnd: e.target.value })}/></label><label><span>Срок оплаты</span><input type="date" value={invoiceForm.dueAt} onChange={(e) => setInvoiceForm({ ...invoiceForm, dueAt: e.target.value })}/></label><label><span>Валюта</span><input value={invoiceForm.currency} onChange={(e) => setInvoiceForm({ ...invoiceForm, currency: e.target.value.toUpperCase() })}/></label><label className="span-2"><span>Комментарий</span><textarea value={invoiceForm.notes} onChange={(e) => setInvoiceForm({ ...invoiceForm, notes: e.target.value })}/></label></div>{validation && <div className="form-message">{validation}</div>}<div className="modal-actions"><button type="button" className="secondary-button" onClick={() => invoiceDialog.current?.close()}>Отмена</button><button className="primary-button">Создать черновик</button></div></form></dialog>
    <dialog ref={lineDialog} className="modal"><form onSubmit={submitLine}><div className="modal-header"><div><span className="eyebrow">{selectedInvoice?.invoiceNumber}</span><h2>Добавить позицию</h2></div><button type="button" className="icon-button" onClick={() => lineDialog.current?.close()}>×</button></div><div className="form-grid"><label><span>Тип</span><select value={lineForm.lineType} onChange={(e) => setLineForm({ ...lineForm, lineType: e.target.value })}><option value="subscription">Подписка</option><option value="license">Лицензия</option><option value="usage">Использование</option><option value="adjustment">Корректировка</option></select></label><label><span>Описание</span><input value={lineForm.description} onChange={(e) => setLineForm({ ...lineForm, description: e.target.value })}/></label><label><span>Количество</span><input type="number" step="0.01" value={lineForm.quantity} onChange={(e) => setLineForm({ ...lineForm, quantity: Number(e.target.value) })}/></label><label><span>Цена</span><input type="number" value={lineForm.unitPrice} onChange={(e) => setLineForm({ ...lineForm, unitPrice: Number(e.target.value) })}/></label><label><span>Скидка</span><input type="number" value={lineForm.discountAmount} onChange={(e) => setLineForm({ ...lineForm, discountAmount: Number(e.target.value) })}/></label><label><span>Налог, %</span><input type="number" step="0.01" value={lineForm.taxRate} onChange={(e) => setLineForm({ ...lineForm, taxRate: Number(e.target.value) })}/></label></div>{validation && <div className="form-message">{validation}</div>}<div className="modal-actions"><button type="button" className="secondary-button" onClick={() => lineDialog.current?.close()}>Отмена</button><button className="primary-button">Добавить</button></div></form></dialog>
    <dialog ref={paymentDialog} className="modal"><form onSubmit={submitPayment}><div className="modal-header"><div><span className="eyebrow">Payment</span><h2>Записать поступление</h2></div><button type="button" className="icon-button" onClick={() => paymentDialog.current?.close()}>×</button></div><div className="form-grid"><label><span>Компания</span><select value={paymentForm.organizationId} onChange={(e) => setPaymentForm({ ...paymentForm, organizationId: e.target.value })}>{data.organizations.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label><span>Сумма</span><input type="number" value={paymentForm.amount} onChange={(e) => setPaymentForm({ ...paymentForm, amount: Number(e.target.value) })}/></label><label><span>Метод</span><select value={paymentForm.method} onChange={(e) => setPaymentForm({ ...paymentForm, method: e.target.value as PaymentMethod })}><option value="bank_transfer">Банковский перевод</option><option value="kaspi">Kaspi</option><option value="card">Карта</option><option value="cash">Наличные</option><option value="manual">Ручной</option></select></label><label><span>Дата поступления</span><input type="date" value={paymentForm.receivedAt} onChange={(e) => setPaymentForm({ ...paymentForm, receivedAt: e.target.value })}/></label><label><span>Внешний номер</span><input value={paymentForm.externalReference} onChange={(e) => setPaymentForm({ ...paymentForm, externalReference: e.target.value })}/></label><label><span>Плательщик</span><input value={paymentForm.payerName} onChange={(e) => setPaymentForm({ ...paymentForm, payerName: e.target.value })}/></label></div>{validation && <div className="form-message">{validation}</div>}<div className="modal-actions"><button type="button" className="secondary-button" onClick={() => paymentDialog.current?.close()}>Отмена</button><button className="primary-button">Записать</button></div></form></dialog>
    <dialog ref={allocationDialog} className="modal"><form onSubmit={submitAllocation}><div className="modal-header"><div><span className="eyebrow">Allocation</span><h2>Распределить платёж</h2></div><button type="button" className="icon-button" onClick={() => allocationDialog.current?.close()}>×</button></div><div className="form-grid"><label className="span-2"><span>Счёт</span><select value={allocationForm.invoiceId} onChange={(e) => setAllocationForm({ ...allocationForm, invoiceId: e.target.value })}><option value="">Выберите счёт</option>{data.invoices.filter((item) => item.organizationId === data.payments.find((payment) => payment.id === allocationForm.paymentId)?.organizationId && item.outstandingTotal > 0).map((item) => <option key={item.id} value={item.id}>{item.invoiceNumber} · {money(item.outstandingTotal, item.currency)}</option>)}</select></label><label className="span-2"><span>Сумма</span><input type="number" value={allocationForm.amount} onChange={(e) => setAllocationForm({ ...allocationForm, amount: Number(e.target.value) })}/></label></div>{validation && <div className="form-message">{validation}</div>}<div className="modal-actions"><button type="button" className="secondary-button" onClick={() => allocationDialog.current?.close()}>Отмена</button><button className="primary-button">Распределить</button></div></form></dialog>
    <dialog ref={refundDialog} className="modal"><form onSubmit={submitRefund}><div className="modal-header"><div><span className="eyebrow">Refund</span><h2>Запросить возврат</h2></div><button type="button" className="icon-button" onClick={() => refundDialog.current?.close()}>×</button></div><div className="form-grid"><label className="span-2"><span>Сумма</span><input type="number" value={refundForm.amount} onChange={(e) => setRefundForm({ ...refundForm, amount: Number(e.target.value) })}/></label><label className="span-2"><span>Причина</span><textarea rows={4} value={refundForm.reason} onChange={(e) => setRefundForm({ ...refundForm, reason: e.target.value })}/></label></div>{refundForm.amount >= 500000 && <div className="warning-box"><AlertTriangle size={16}/> Возврат от 500 000 ₸ потребует двух независимых согласований.</div>}{validation && <div className="form-message">{validation}</div>}<div className="modal-actions"><button type="button" className="secondary-button" onClick={() => refundDialog.current?.close()}>Отмена</button><button className="danger-button">Создать запрос</button></div></form></dialog>
  </>;
}
